/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Species = IDL.Variant({
  'extraterrestrialBeing' : IDL.Null,
  'galacticHuman' : IDL.Null,
  'roboticEntity' : IDL.Null,
  'unknown' : IDL.Null,
});
export const IndividualInput = IDL.Record({
  'name' : IDL.Text,
  'homeworld' : IDL.Text,
  'peaceScore' : IDL.Nat,
  'species' : Species,
});
export const Individual = IDL.Record({
  'name' : IDL.Text,
  'homeworld' : IDL.Text,
  'peaceScore' : IDL.Nat,
  'species' : Species,
});

export const idlService = IDL.Service({
  'addIndividual' : IDL.Func([IndividualInput], [], []),
  'applyDynamicDrift' : IDL.Func([], [], []),
  'deleteIndividual' : IDL.Func([IDL.Text], [], []),
  'getAllIndividualsRanked' : IDL.Func([], [IDL.Vec(Individual)], ['query']),
  'getIndividualStats' : IDL.Func([], [IDL.Nat, IDL.Float64], ['query']),
  'seedInitialIndividuals' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
  'updateScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Species = IDL.Variant({
    'extraterrestrialBeing' : IDL.Null,
    'galacticHuman' : IDL.Null,
    'roboticEntity' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const IndividualInput = IDL.Record({
    'name' : IDL.Text,
    'homeworld' : IDL.Text,
    'peaceScore' : IDL.Nat,
    'species' : Species,
  });
  const Individual = IDL.Record({
    'name' : IDL.Text,
    'homeworld' : IDL.Text,
    'peaceScore' : IDL.Nat,
    'species' : Species,
  });
  
  return IDL.Service({
    'addIndividual' : IDL.Func([IndividualInput], [], []),
    'applyDynamicDrift' : IDL.Func([], [], []),
    'deleteIndividual' : IDL.Func([IDL.Text], [], []),
    'getAllIndividualsRanked' : IDL.Func([], [IDL.Vec(Individual)], ['query']),
    'getIndividualStats' : IDL.Func([], [IDL.Nat, IDL.Float64], ['query']),
    'seedInitialIndividuals' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
    'updateScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };