/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IndividualInput {
    name: string;
    homeworld: string;
    peaceScore: bigint;
    species: Species;
}
export interface Individual {
    name: string;
    homeworld: string;
    peaceScore: bigint;
    species: Species;
}
export enum Species {
    extraterrestrialBeing = "extraterrestrialBeing",
    galacticHuman = "galacticHuman",
    roboticEntity = "roboticEntity",
    unknown_ = "unknown"
}
export interface backendInterface {
    addIndividual(input: IndividualInput): Promise<void>;
    applyDynamicDrift(): Promise<void>;
    deleteIndividual(name: string): Promise<void>;
    getAllIndividualsRanked(): Promise<Array<Individual>>;
    getIndividualStats(): Promise<[bigint, number]>;
    seedInitialIndividuals(number: bigint): Promise<bigint | null>;
    updateScore(name: string, newScore: bigint): Promise<void>;
}
import type { Individual as _Individual, IndividualInput as _IndividualInput, Species as _Species } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addIndividual(arg0: IndividualInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIndividual(to_candid_IndividualInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIndividual(to_candid_IndividualInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async applyDynamicDrift(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyDynamicDrift();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyDynamicDrift();
            return result;
        }
    }
    async deleteIndividual(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIndividual(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIndividual(arg0);
            return result;
        }
    }
    async getAllIndividualsRanked(): Promise<Array<Individual>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIndividualsRanked();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIndividualsRanked();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIndividualStats(): Promise<[bigint, number]> {
        if (this.processError) {
            try {
                const result = await this.actor.getIndividualStats();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIndividualStats();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async seedInitialIndividuals(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.seedInitialIndividuals(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedInitialIndividuals(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateScore(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScore(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Individual_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Individual): Individual {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Species_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Species): Species {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    homeworld: string;
    peaceScore: bigint;
    species: _Species;
}): {
    name: string;
    homeworld: string;
    peaceScore: bigint;
    species: Species;
} {
    return {
        name: value.name,
        homeworld: value.homeworld,
        peaceScore: value.peaceScore,
        species: from_candid_Species_n8(_uploadFile, _downloadFile, value.species)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    extraterrestrialBeing: null;
} | {
    galacticHuman: null;
} | {
    roboticEntity: null;
} | {
    unknown: null;
}): Species {
    return "extraterrestrialBeing" in value ? Species.extraterrestrialBeing : "galacticHuman" in value ? Species.galacticHuman : "roboticEntity" in value ? Species.roboticEntity : "unknown" in value ? Species.unknown_ : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Individual>): Array<Individual> {
    return value.map((x)=>from_candid_Individual_n6(_uploadFile, _downloadFile, x));
}
function to_candid_IndividualInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndividualInput): _IndividualInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Species_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Species): _Species {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    homeworld: string;
    peaceScore: bigint;
    species: Species;
}): {
    name: string;
    homeworld: string;
    peaceScore: bigint;
    species: _Species;
} {
    return {
        name: value.name,
        homeworld: value.homeworld,
        peaceScore: value.peaceScore,
        species: to_candid_Species_n3(_uploadFile, _downloadFile, value.species)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Species): {
    extraterrestrialBeing: null;
} | {
    galacticHuman: null;
} | {
    roboticEntity: null;
} | {
    unknown: null;
} {
    return value == Species.extraterrestrialBeing ? {
        extraterrestrialBeing: null
    } : value == Species.galacticHuman ? {
        galacticHuman: null
    } : value == Species.roboticEntity ? {
        roboticEntity: null
    } : value == Species.unknown_ ? {
        unknown: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
